# Generated by Django 3.0.8 on 2021-03-19 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('activeIndicator', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('orgRegNumber', models.CharField(max_length=26, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pharmacyName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RespiratoryRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedBy', models.CharField(choices=[('Self', 'User'), ('Doctor', 'Doctor')], max_length=6)),
                ('hospitalOrClinic', models.CharField(max_length=50, null=True)),
                ('doctorName', models.CharField(max_length=20, null=True)),
                ('prescriptionDate', models.DateField(default=datetime.date.today)),
                ('contactNumber', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('symptoms', models.TextField(max_length=255, null=True)),
                ('medicines', models.TextField(max_length=255, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('prescriptionAttachment', models.ImageField(null=True, upload_to='')),
                ('prescriberId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriberId', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPractitionerInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
                ('licenseNumber', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('activeIndicator', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('orgId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appV1.OrganizationInfo')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuranceProvider', models.CharField(max_length=50)),
                ('policyNumber', models.CharField(max_length=20, unique=True)),
                ('policyName', models.CharField(max_length=50)),
                ('validTill', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relativeName', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=20)),
                ('primaryContactNumber', models.CharField(max_length=10)),
                ('secondaryContactNumber', models.CharField(max_length=10, null=True)),
                ('relativeAddress', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodyTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
