# Generated by Django 3.0.8 on 2021-05-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0002_auto_20210427_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='middleName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
