# Generated by Django 3.2.2 on 2021-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0004_auto_20210503_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='fingerprint',
            field=models.ImageField(null=True, upload_to='fingerprints/'),
        ),
    ]
