# Generated by Django 3.2.2 on 2021-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0005_personalinfo_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='profile_picture/'),
        ),
    ]
