# Generated by Django 3.2.2 on 2021-06-26 00:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appV1', '0008_insuranceagentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('validTill', models.DateField(null=True)),
                ('policyProvider', models.CharField(max_length=30, null=True)),
                ('policyName', models.CharField(max_length=30, null=True)),
                ('policyNumber', models.CharField(max_length=30, null=True)),
                ('agentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enroll_agent_id', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
