# Generated by Django 3.2.2 on 2021-06-26 04:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appV1', '0009_enrollinsurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientToAgentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('healthrisk', models.IntegerField(default=30, null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('agentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pta_agent_id', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pta_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
