# Generated by Django 3.2.2 on 2021-06-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0010_patienttoagentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttoagentrequest',
            name='healthrisk',
        ),
        migrations.AlterField(
            model_name='patienttoagentrequest',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
