# Generated by Django 3.2.2 on 2021-06-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0011_auto_20210629_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceagentinfo',
            name='tags',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
