# Generated by Django 3.2.2 on 2021-06-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0012_alter_insuranceagentinfo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceagentinfo',
            name='tags',
        ),
    ]
