# Generated by Django 3.2.2 on 2021-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0014_allergicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttoagentrequest',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
