# Generated by Django 3.2.2 on 2021-07-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0016_recentactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessverification',
            old_name='blood_pressure_field',
            new_name='lab_report_field',
        ),
    ]
