# Generated by Django 3.2.2 on 2021-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0017_rename_blood_pressure_field_accessverification_lab_report_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreportinfo',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
